FROM registry.gitlab.gnome.org/world/openpaperwork/paperwork/build

# Paperwork dev documentation dependencies

# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
RUN mkdir -p /usr/share/man/man1 && \
	apt-get install -y -q \
	openjdk-11-jre

RUN apt-get install -y -q \
	plantuml \
	python3-recommonmark \
	python3-sphinx \
	python3-sphinxcontrib.plantuml
